### ISSUE TITLE
FR: Line comments that incorporate text

### ISSUE THREAD

**Issue by StephanRoemer** [LudoPinelli/comment-box.nvim#10]
Hey Ludo!

Thanks for this amazing plugin!
I wanted to ask, if you would consider implementing another category: lines with text.
The result would look like this:

`--- This is a header ---------------------------`

As a basis, I would suggest to use the templates from the "cbline" category.

Thanks for considering!

**Comment by LudoPinelli** [comment]
Sorry for the very late answer. It was part of the few ideas I had to add, but as you can see I didn't work on the plugin for quite some time... I'll do my best in the coming few weeks to give some updates.

**Comment by StephanRoemer** [comment]
No worries, take your time and thanks for getting back to me!

Cheers!

**Comment by LudoPinelli** [comment]
Done!
I called them "titled lines" and made sure they are as flexible as the boxes. I hope they reach your expectation, but if not please let me know! :)

**Comment by okuma10** [comment]
Does that still work with the CBline?

**Comment by LudoPinelli** [comment]
Yes, the CBline still works but it's for line without text.
