### ISSUE TITLE
CBlbox not producing left aligned text in TypeScript

### ISSUE THREAD

**Issue by benfrain** [LudoPinelli/comment-box.nvim#13]
Thanks for making this plugin, looks to be very useful. 

When I do `CBlbox` in Lua I get left hand box and text as expected like this:

```lua
--  ╭──────────────────────────────────────────────────────────╮
--  │ gets the initial json loaded for excerpts                │
--  ╰──────────────────────────────────────────────────────────╯
```

However, the same command in a Typescript file gives this (not left aligned text)

```javascript
// ╭──────────────────────────────────────────────────────────╮
// │         gets the initial json loaded for excerpts        │
// ╰──────────────────────────────────────────────────────────╯
```

Presumably this is because it has some issue with TypeScript as when I use a vanilla js file I get the expected result:

```javascript
// ╭──────────────────────────────────────────────────────────╮
// │ gets the initial json loaded for excerpts                │
// ╰──────────────────────────────────────────────────────────╯
```

Is there a way to associate typescript with the javascript pattern?

**Comment by amaanq** [comment]
can't reproduce, I get this in a typescript file:

```
// ╭──────────────────────────────────────────────────────────────────────────────╮
// │  gets the initial json loaded for excerpts                                   │
// ╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by benfrain** [comment]
Hmmm, just tried on another system and it works as expected there too. Closing ads can’t replicate outside that one machine. Thanks for trying it out 👍
