### ISSUE TITLE
It is recommended to change `impl.lua` to `init.lua` or `comment-box.lua`

### ISSUE THREAD

**Issue by liaohui5** [LudoPinelli/comment-box.nvim#18]
```lua
require("comment-box").setup()  -- module `comment-box` not found

require("comment-box.impl").setup() -- working
```

![image](https://user-images.githubusercontent.com/29266093/221918064-79038273-c98c-486b-85ae-892d449b8f3d.png)

**Comment by LudoPinelli** [comment]
Hi @liaohui5,
I don't know why it works on my machine, I can't test it right now but I will later tonight. My guess is that I have to rename the file `/plugin/comment-box.lua` by `/plugin/init.lua`.
Thanks for reporting this issue.

**Comment by kohane27** [comment]
https://github.com/LudoPinelli/comment-box.nvim/pull/19 addressing this issue. Thanks!

**Comment by kohane27** [comment]
can confirm that the commit 74ad9fc05b456e1e0f12a6a623dbe375dabbbfa9 (https://github.com/LudoPinelli/comment-box.nvim/pull/19) works. Thank you for merging and fixing this issue!

**Comment by LudoPinelli** [comment]
Thanks for the feedback!
