### ISSUE TITLE
the indentation disappear

### ISSUE THREAD

**Issue by nyngwang** [LudoPinelli/comment-box.nvim#2]
## before

<img src="https://user-images.githubusercontent.com/24765272/149659306-fa7fc31f-dcf1-40a3-86b2-e1598d113032.png" width="700">

## after
<img src="https://user-images.githubusercontent.com/24765272/149659327-57ba6c6c-a4fc-4c69-bce4-d1be23704f39.png" width="700">

## idea

- spaces are also info. provided by the user, should be recorded too.
- as the pic. shown, if would be great to visually include two more lines (since top&bottom borders are added) in the result selection.

The other things are all great. Thanks for the cool plugin :)

**Comment by LudoPinelli** [comment]
> ## idea
> * spaces are also info. provided by the user, should be recorded too.

Absolutely! I'll look into it.

> * as the pic. shown, if would be great to visually include two more lines (since top&bottom borders are added) in the result selection.

I have no idea how to do that, but I'll look into it too :)

Thanks for your feedback!

**Comment by LudoPinelli** [comment]
Problems solved :)
