### ISSUE TITLE
Extract text out of the box

### ISSUE THREAD

**Issue by ShinyZero0** [LudoPinelli/comment-box.nvim#22]
It'd be nice to have a command to extract text out of the box (remove the box and leave only the text) or quickly yank the entire content of box to edit it or change the box style.

**Comment by LudoPinelli** [comment]
I guess it would require a kind of parser to be able to do that and I unfortunately don't have the knowledge required right now, but I keep the suggestion for the future!

**Comment by ShinyZero0** [comment]
Well i kinda did that for one line texts with a macro `dd0dw$dawjdd`

**Comment by LudoPinelli** [comment]
Hello,
You can now delete a box (while keeping the text) with the command `CBdbox`. The box must be entirely selected for it to work though.
I keep this issue open until I add a command that yank only the content of a box.
