### ISSUE TITLE
Are the Keybindings examples about accbox incorrect? 

### ISSUE THREAD

**Issue by honeway** [LudoPinelli/comment-box.nvim#24]
command: `:lua require("comment-box").accbox()` 

![image](https://user-images.githubusercontent.com/6339134/236591269-289098d3-0c6e-47f7-a9d6-799ad82065d3.png)

**Comment by killerqueer** [comment]
It looks like the correct command for center adapted boxes is actually:

`:lua require("comment-box").ccbox()` and **NOT** `:lua require("comment-box").accbox()`

[The docs](https://github.com/LudoPinelli/comment-box.nvim/blob/6672213bd5d2625a666a297b66307967effa50bc/doc/comment-box.txt) have a table with all of the correct command options.

**Comment by LudoPinelli** [comment]
Yes, sorry about that, I updated the README, thanks!
