### ISSUE TITLE
[BUG]: The comment_string of some filetypes will contain trailing space

### ISSUE THREAD

**Issue by MasouShizuka** [LudoPinelli/comment-box.nvim#26]
Take the `CBllbox` command as an example.

In the `python` file,
before:
```python
# test
```
after:
```python
#  ╭──────────────────────────────────────────────────────────╮
#  │ fuck                                                     │
#  ╰──────────────────────────────────────────────────────────╯
```
The comment_string is `# `.

In the `lua` file,
before:
```lua
-- test
```
after:
```lua
--  ╭──────────────────────────────────────────────────────────╮
--  │ test                                                     │
--  ╰──────────────────────────────────────────────────────────╯
```
The comment_string is `-- `.

In the `rust` file,
before:
```rust
// test
```
after:
```lua
// ╭──────────────────────────────────────────────────────────╮
// │  test                                                    │
// ╰──────────────────────────────────────────────────────────╯
```
The comment_string is `//`, and does not contain space.

It can be seen that some filetypes are separated by 2 spaces, and some are separated by 1 space.
In the former, I found that it contains space by printing `comment_string`, such as `# ` in Python.

Is there something wrong with my configuration?

Also, I think this can be used as a configuration item, that is, the number of spaces between comment and box.
0 means no spaces, etc.

**Comment by LudoPinelli** [comment]
I obtain the same results as yours. I use the built-in `vim.bo.commentstring` to determine the comment_string and it seems that this command doesn't give a consistent/accurate result or I'm missing something, in the former I'm afraid I can't do much about it. A better and definitive solution would be to use a table of the possible comment types as Comment.nvim does but I looked into it and it's beyond what I'm capable to accomplish with my poor understanding of lua and the nvim api right now ^^

For your suggestion to configure the number of spaces between the start of the box and the comment (am I understanding correctly?) I will look into it.

Thanks for your feedback!

**Comment by LudoPinelli** [comment]
Just found a workaround while working on another issue (I just had to trim the `comment_string` after retrieving it). It should work consistently with all filetypes now.

I close this issue but I keep in mind your suggestion. Thanks again for your feedback!

**Comment by MasouShizuka** [comment]
Lines still have redundant spaces.

In the python file:
```python
#  ────────────────────────────────────────────────────────────
# ╭──────────────────────────────────────────────────────────╮
# │ test                                                     │
# ╰──────────────────────────────────────────────────────────╯
#  ────────────────────────────────────────────────────────────
```

**Comment by MasouShizuka** [comment]
By the way, there seems to be a small error in the readme?

![image](https://github.com/LudoPinelli/comment-box.nvim/assets/44764707/f2d694d3-a24f-45ae-8850-b46ed894c37f)

**Comment by LudoPinelli** [comment]
You're right in both cases! Should be fixed now. Thank you!
