### ISSUE TITLE
[Bug] Misalignment due to unstripped input

### ISSUE THREAD

**Issue by alexmozaidze** [LudoPinelli/comment-box.nvim#28]
# Bug

Spaces before input don't get stripped, which results in a misaligned box.

If the input is **not** a comment, spaces *after* the input get preserved as well.

## Reproduction

1. Have some input (note the spaces after the input)

```lua
    my thing       
--    my thing       
```

2. Run `:CBalbox` on each line

```lua
--  ╭──────────────────────╮
--  │      my thing        │
--  ╰──────────────────────╯
--  ╭─────────────╮
--  │    my thing │
--  ╰─────────────╯
```

## Potential solution

Pipe the input through `vim.trim()`

```lua
local input = "    my thing       "
input = vim.trim(input) -- => "my thing"
```

**Comment by LudoPinelli** [comment]
Thanks for your feedback! I use vim.trim() but it seems I missed a place where I should have, I'll look into it.

**Comment by LudoPinelli** [comment]
Fixed, thanks again!
