### ISSUE TITLE
:CLxyline[num] commands don't pick style number while lua API calls work

### ISSUE THREAD

**Issue by madlabman** [LudoPinelli/comment-box.nvim#31]
<img width="315" alt="image" src="https://github.com/LudoPinelli/comment-box.nvim/assets/10616301/f18ae644-0595-4154-8961-8404e61ccfd2">

<img width="498" alt="image" src="https://github.com/LudoPinelli/comment-box.nvim/assets/10616301/109be72a-20e4-49e1-832f-81a4223d4832">

I'm on be441e6

```
❯ nvim --version
NVIM v0.9.5
Build type: Release
```

**Comment by LudoPinelli** [comment]
Thank you for your report. It should be fixed now :)
