### ISSUE TITLE
doc: Incorrect commands

### ISSUE THREAD

**Issue by abhijeetviswa** [LudoPinelli/comment-box.nvim#32]
Setting this plugin up myself, and so far it's pretty amazing. So a couple of possible discrepancies/omissions in the documentation:

1. In the section explaining the command structure: 

> Exceptions:
>  &nbsp;&nbsp; Adapted boxes: x is a (for adapted) y is the position of the box.

I noticed that you x and y values can be swapped around i.e `CBlabox` seems equivalent to `CBalbox` 

2. In the [Commands->Boxes](https://github.com/LudoPinelli/comment-box.nvim#boxes) section, the second to last entry in the table `CBbaox[num]` is incorrect. It should be `CBacbox[num]`.

Nice work on the plugin.

**Comment by LudoPinelli** [comment]
I'm glad you like it so far!

> 1. In the section explaining the command structure:
> 
> > Exceptions:
> >    Adapted boxes: x is a (for adapted) y is the position of the box.
> 
> I noticed that you x and y values can be swapped around i.e `CBlabox` seems equivalent to `CBalbox`

I used `CBalbox`, `CBacbox` and `CBarbox` when I wrote the plugin at first, but for consistency in the nomenclature, those are deprecated in favor of `CBlabox`, `CBcabox` and `CBrabox`. And you're right, the explanation in the doc is not clear, I changed it a bit, I will replace the image for clarity later today.
 
> 2. In the [Commands->Boxes](https://github.com/LudoPinelli/comment-box.nvim#boxes) section, the second to last entry in the table `CBbaox[num]` is incorrect. It should be `CBacbox[num]`.

Fixed, thank you!
