### ISSUE TITLE
Line parameters have no effect

### ISSUE THREAD

**Issue by savchenko** [LudoPinelli/comment-box.nvim#38]
Configured with:

```lua
line = {
        line = "-",
        line_start = "+",
        line_end = "+",
        title_left = "[",
        title_right = "]",
},
```

Executing `:CBllline` and/or `:CBccline` still creates line like this:

```lua
-- ── Yes, just like this one ────────────────────────────────────────────────────
```

Interestingly, `borders{}` works as expected and `:CBclbox` correctly uses chosen set of characters.

**Comment by LudoPinelli** [comment]
Thank you, I'll look into it!

**Comment by LudoPinelli** [comment]
The problem is in your config: replace `line = {` with `lines = {` :)

**Comment by The-Plottwist** [comment]
Same problem at the Readme too ```line = ...``` whereas it should be ```line(s) = ... ```.
Side Note: Ahh... it got Me headaches xD

**Comment by LudoPinelli** [comment]
Oh god, sorry about that :sweat:, README and doc fixed, thanks!
