### ISSUE TITLE
Not working for `.zshrc`

### ISSUE THREAD

**Issue by edwardbaeg** [LudoPinelli/comment-box.nvim#41]
The plugin does not insert as comments in `.zshrc` files.

Before:
```
test
```

After `CBccbox`:
```
           ╭───────────────────────────────────────────────────────────╮
           │                           test                            │
           ╰───────────────────────────────────────────────────────────╯
```

Expected:
```
#          ╭───────────────────────────────────────────────────────────╮
#          │                           test                            │
#          ╰───────────────────────────────────────────────────────────╯
```

**Comment by LudoPinelli** [comment]
Added, thank you!

**Comment by edwardbaeg** [comment]
Thanks for the quick fix!

However, I am still having the issue. I have updated the plugin. If I run `set filetype?` I get `zsh` and so I would have expected your changes to have worked.

**Comment by edwardbaeg** [comment]
Actually, I had to remove `comment_style = "auto"` for this to work with box comments. If I understand this configuration setting, I would have expected the `auto` style to have worked properly in using line style comments for zsh as there isn't a block style available.

**Comment by LudoPinelli** [comment]
> Actually, I had to remove `comment_style = "auto"` for this to work with box comments. If I understand this configuration setting, I would have expected the `auto` style to have worked properly in using line style comments for zsh as there isn't a block style available.

Well, it's a bug, it should work as you expected! I will look into it, thank you for letting me know!

**Comment by LudoPinelli** [comment]
Fixed, thanks again :)
